// Data access layer. Three targets:
//
//   1. plugin  -- the WordPress plugin. Ships its own reference layer and reads
//      Supabase live. Built by `npm run build:plugin`, which bakes the target in.
//   2. pages   -- the GitHub Pages demo. Same overlay, bundled files come from
//      the static export instead of the plugin directory.
//   3. dev     -- `npm run dev`, talking to the backend API. No bundled layer.
//
// Every target layers Supabase over a bundled reference layer. They differ only
// in where the bundled files sit and where the Supabase config comes from, so
// the overlay is written once and both builds share it.
//
// Why the target is a build-time constant rather than a runtime check for
// `window.jceConfig`: the plugin has to work without any PHP cooperating. If
// "am I the plugin?" is answered by a global that only the plugin's PHP sets,
// then a missing or misnamed global silently turns the shipped plugin into the
// dev target, which fetches /api and renders nothing. That failure is invisible
// until someone loads the page. Baking the target means the shipped bundle
// cannot be the wrong one.
//
// The Supabase config is baked the same way. That is what lets the plugin be
// uploaded once and then track Supabase forever: the anon key is a publishable
// key, not a credential, so embedding it grants nothing that RLS would not
// already grant to anyone who loads the page. Changing data means changing the
// database, not re-uploading a zip. window.jceConfig still wins when present,
// so a site that would rather configure PHP can, and the two can disagree
// without either build changing.

// The plugin's own directory, derived from the URL its script was served from.
// This is the one thing that genuinely cannot be known at build time: WordPress
// decides the plugins URL, and it differs per install. currentScript is read
// during initial evaluation, which is before any async fetch, so the src is
// still the bundle's own tag rather than a later injected script.
function pluginAssetBase() {
  if (typeof document === 'undefined') return '';
  const src = document.currentScript?.src;
  return src ? src.slice(0, src.lastIndexOf('/') + 1) : '';
}

const WP = typeof window !== 'undefined' ? window.jceConfig : null;
const TARGET = import.meta.env.VITE_TARGET || 'dev';
const PLUGIN = TARGET === 'plugin';
const STATIC = TARGET === 'pages' || import.meta.env.VITE_STATIC === '1';
const CYCLE = WP?.cycle || import.meta.env.VITE_CYCLE || '2026';
const BASE = import.meta.env.BASE_URL || '/';
const API_BASE = (import.meta.env.VITE_API_BASE || '/api').replace(/\/$/, '');

// Root of the bundled files, before the reference/ or geo/ subdirectory. The
// plugin serves them from its own directory; Pages serves them from the site
// root that Vite reports as BASE_URL.
const ASSET_BASE = PLUGIN
  ? (WP?.assetBase || pluginAssetBase())
  : BASE.endsWith('/') ? BASE : `${BASE}/`;

// Where the invariant reference layer lives, relative to that root. These are
// two different directories on purpose: the plugin's reference layer is the
// shipped product, so it is versioned with the code, while demo-data is
// regenerated by export-static.mjs on every deploy.
const REFERENCE_BASE = PLUGIN ? `${ASSET_BASE}data/reference/` : `${ASSET_BASE}demo-data/`;

const SUPABASE_URL = WP?.supabaseUrl || import.meta.env.VITE_SUPABASE_URL || '';
const SUPABASE_KEY = WP?.supabaseAnonKey || import.meta.env.VITE_SUPABASE_ANON_KEY || '';
// Supabase is a live overlay on the bundled layer, so it is used whenever it is
// configured. Without an endpoint the app still renders from bundled data.
const LIVE = Boolean(SUPABASE_URL && SUPABASE_KEY);
// Only the plugin and Pages ship a reference layer; dev has none and talks to
// the backend API instead.
const BUNDLED = PLUGIN || STATIC;

export const isStatic = STATIC;
export const isWordPress = PLUGIN;
export const isBundled = BUNDLED;

// Fetch with a one-shot fallback. `primary` is the live source, `fallback` the
// bundled reference. A fallback failure is fatal; a primary failure is reported
// once so the console says why the page is showing only bundled data.
const warned = new Set();

async function getJson(url) {
  // GitHub Pages serves static assets with cache headers, and a stale
  // demo-data JSON would leave the map showing an older race set (e.g. an
  // NC-only U.S. Senate map) after a redeploy. Never reuse cached demo data.
  const res = await fetch(url, STATIC ? { cache: 'no-store' } : undefined);
  if (!res.ok) throw new Error(`${res.status} ${url}`);
  return res.json();
}

async function withFallback(label, primary, fallback) {
  try {
    return await primary();
  } catch (err) {
    if (!warned.has(label)) {
      warned.add(label);
      console.warn(`[jce] ${label} unavailable (${err.message}); using the bundled reference`);
    }
    return fallback();
  }
}

// For reads that overlay onto a bundled base rather than replace it. A failure
// is the expected steady state until the orchestrators are live, so it resolves
// to null and the caller keeps the bundled record instead of unwinding.
async function awaitQuietly(label, primary) {
  try {
    return await primary();
  } catch (err) {
    if (!warned.has(label)) {
      warned.add(label);
      console.warn(`[jce] ${label} unavailable (${err.message}); showing bundled reference data only`);
    }
    return null;
  }
}

// --- WordPress / Supabase ---------------------------------------------------

async function rpc(fn, params = {}) {
  if (!LIVE) throw new Error('no Supabase endpoint configured');
  const url = new URL(`/rest/v1/rpc/${fn}`, SUPABASE_URL);
  for (const [k, v] of Object.entries(params)) url.searchParams.set(k, v);
  // PostgREST returns 401 without the apikey, even for a public read, so the
  // anon key is not optional here.
  return fetch(url.toString(), {
    headers: { apikey: SUPABASE_KEY, Authorization: `Bearer ${SUPABASE_KEY}` },
  }).then(async (res) => {
    if (!res.ok) throw new Error(`${res.status} ${fn}`);
    return res.json();
  });
}

// A file that ships inside the plugin or the site root, addressed from the
// target's own base. The geometry lives beside the reference layer rather than
// inside it: boundaries change once a redistricting cycle, so it is shipped
// rather than fetched.
function wpAsset(rel) {
  return new URL(rel, ASSET_BASE).toString();
}

// The reference layer is the guaranteed floor, not a fallback. It is a static
// file, so it resolves without a network and without Supabase, and it carries
// only what does not move: candidate names, the Civitas lean, and which seats
// are in play. 170 of the 185 seats have no polling, no market and no
// fundraising at all, so for 92% of the map this is the whole content and the
// page is fully readable with Supabase absent.
//
// Volatile data is layered on top from Supabase when it answers. It is never
// substituted for a bundled number: a hand-entered poll or a live market price
// that is not in Supabase is left missing and rendered as unavailable. Swapping
// in a stale copy of a price would be worse than showing none, because a stale
// price looks exactly like a live one.
function wpReference(rel) {
  return getJson(`${REFERENCE_BASE}${rel}`);
}

// The bundled record for the current target, by race type or district. Both
// builds ship the same normalised model, so the Supabase overlay is written
// once against it.
function bundled(rel) {
  return wpReference(rel);
}

// Static files that ship in both builds, so the same <img> works whichever host
// is serving. In the plugin they come off the plugin directory; on Pages they
// are served from the site root.
//
// Joined as strings rather than resolved with new URL(), because BASE_URL is
// root-relative ("/" or "/nc26/") and the URL constructor requires an absolute
// base -- it throws "Invalid URL" on exactly the values Pages supplies. That
// throw happened inside render, so React tore down the whole tree and the page
// went blank with no partial fallback. ASSET_BASE is absolute on the plugin
// branch, so new URL() is safe there and is kept.
export function assetUrl(rel) {
  if (PLUGIN) return wpAsset(rel);
  const base = import.meta.env.BASE_URL || '/';
  return base.endsWith('/') ? base + rel : `${base}/${rel}`;
}

// Attach geometry to a map payload, keyed by district_id.
//
// In the plugin, geometry ships beside the reference layer rather than inside
// it, because it is 636 KB of the total and changes only at a redistricting.
// The Pages build bakes geometry directly into each map file, so there the
// bundled features already carry it and this is a no-op. Merging by
// district_id rather than by position is what keeps a seat added on one side
// from shifting every later feature onto the wrong shape.
async function withGeometry(payload, raceType) {
  if (!PLUGIN) return payload;
  const geo = await getJson(wpAsset(`data/geo/${raceType}.json`));
  const shapes = new Map(geo.features.map((f) => [f.district_id, f.geometry]));
  return {
    ...payload,
    features: (payload.features || []).map((f) => ({ ...f, geometry: shapes.get(f.district_id) || null })),
  };
}

// Overlay Supabase's volatile fields onto a bundled record. Field-level and
// additive: only keys Supabase actually returned are copied, so an absent or
// partial payload leaves the bundled invariant fields intact rather than
// replacing the record with nulls.
function overlayVolatile(base, live) {
  if (!live) return base;
  const out = { ...base };
  for (const [k, v] of Object.entries(live)) {
    if (v == null) continue;
    out[k] = v;
  }
  return out;
}

// Same, for the map. Features merge by district_id; the races array is matched
// by district_id too rather than by position, so a seat added on one side
// cannot shift every later row onto the wrong race.
function overlayMap(base, live) {
  if (!live) return base;
  const liveFeatures = new Map((live.features || []).map((f) => [f.district_id, f]));
  return {
    ...base,
    features: base.features.map((f) => {
      const l = liveFeatures.get(f.district_id);
      if (!l) return f;
      const merged = { ...f };
      if (l.metrics) merged.metrics = l.metrics;
      return merged;
    }),
    races: base.races.map((r) => overlayVolatile(r, live.races?.find((x) => x.district_id === r.district_id))),
  };
}

// --- public surface ---------------------------------------------------------

export function getMeta() {
  // The reference meta is the cycle, the race-type counts and the provenance
  // block -- all invariant, so the gauges' outlook figures are the only part
  // that can be missing. MiniGauge returns null without an outlook, which
  // leaves the tab absent rather than showing an empty dial.
  if (LIVE) {
    return bundled('meta.json').then((base) =>
      withFallback('meta',
        () => rpc('meta', { p_cycle: CYCLE }).then((m) => ({
          ...base,
          ...m,
          // The demo payload nests the gauges one-per-chamber; keep the shape the
          // components expect so there is a single contract across all targets.
          // A key Supabase omits falls back to the bundled value rather than
          // null: a missing outlook should leave the tab absent, not blank a
          // gauge the build already knows the answer for.
          house_outlook: m.outlooks?.us_house ?? base.house_outlook ?? null,
          senate_outlook: m.outlooks?.us_senate ?? base.senate_outlook ?? null,
          nc_senate_outlook: m.outlooks?.nc_senate ?? base.nc_senate_outlook ?? null,
          nc_house_outlook: m.outlooks?.nc_house ?? base.nc_house_outlook ?? null,
        })),
        () => base));
  }
  return getJson(`${API_BASE}/meta`);
}

export function getMap(raceType) {
  if (LIVE) {
    return bundled(`map/${raceType}.json`).then((base) =>
      withGeometry(overlayMap(base,
        // A failed read is normal, not exceptional: it resolves to the bundled
        // map so the page is still readable.
        awaitQuietly(`map:${raceType}`, () => rpc('map_payload', { p_race_type: raceType, p_cycle: CYCLE })),
      ), raceType));
  }
  return getJson(`${API_BASE}/map?race_type=${raceType}`);
}

export function getRace(districtId) {
  if (BUNDLED) {
    // Reference-only for now. Per-seat volatile reads (polls, money, news) have
    // no Supabase endpoint defined yet, so the bundled invariant record is the
    // whole payload rather than a fallback -- the panel renders its unavailable
    // states and the seat is still fully readable.
    return wpReference(`race/${districtId}.json`).catch(() => {
      throw new Error(`race ${districtId} not in the bundled reference layer`);
    });
  }
  return getJson(`${API_BASE}/races/${districtId}`);
}

export function getTicker(limit = 12) {
  if (LIVE) {
    // No bundled ticker: every story is by definition newer than the build that
    // shipped it, so a frozen copy would be stale on arrival. With Supabase
    // absent the ticker is simply absent, which is honest.
    return withFallback('ticker',
      () => rpc('ticker', { p_limit: limit }).then((items) => ({ items })),
      () => ({ items: [] }));
  }
  return getJson(`${API_BASE}/ticker?limit=${limit}`);
}

export function getOutline() {
  // The state outline sits beside the reference layer in the plugin
  // (data/outline.json) but inside demo-data on Pages, where the exporter writes
  // the whole set into one directory. So the path is per-target rather than
  // derived from REFERENCE_BASE, which would put it one level too deep on Pages.
  if (PLUGIN) return getJson(wpAsset('data/outline.json'));
  if (STATIC) return getJson(`${REFERENCE_BASE}outline.json`);
  return getJson(`${API_BASE}/outline`);
}